baseURL = "http://marmooo.github.io/shogi-beginners/"
languageCode = "ja-jp"
title = "将棋びぎなーず"
publishDir = "docs"

disableHugoGeneratorInject = true
disableKinds= ["taxonomy"]

[markup.goldmark.renderer]
  unsafe = true
